# Generated by Django 2.2.7 on 2019-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=140)),
                ('cnh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=140)),
                ('status', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('horario_funcionamento', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('modelo_carro', models.CharField(max_length=200)),
                ('status_pagamento', models.CharField(max_length=15)),
                ('forma_pagamento', models.CharField(max_length=15)),
                ('dt_pedido', models.DateTimeField()),
                ('dt_entrega', models.DateTimeField()),
                ('dt_retirada', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerentes', to='app.Concessionaria')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='app.Concessionaria')),
            ],
        ),
    ]
