# Generated by Django 2.2.7 on 2019-11-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191120_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='concessionaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.Concessionaria'),
            preserve_default=False,
        ),
    ]
