# Generated by Django 2.2.7 on 2019-11-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('CC', 'CARTAO CREDITO'), ('CD', 'CARTAO DEBITO'), ('BB', 'BOLETO BANCARIO'), ('TB', 'TRANSFERENCIA BANCARIA'), ('D', 'DINHEIRO')], default='TB', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AB', 'ABERTO'), ('PD', 'PRODUCAO'), ('TP', 'EM TRANSPORTE'), ('EN', 'ENTREGUE'), ('AG', 'AGUARDANDO')], default='AB', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('AG', 'AGUARDANDO'), ('AN', 'ANALISE'), ('AC', 'ACEITO'), ('RE', 'RECUSADO')], default='AG', max_length=15),
        ),
    ]
