# Generated by Django 2.2.7 on 2019-11-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191121_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='protocolo_montadora',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
